Repository Grupo-Olimpo/E-a-Economia, pull requests merged in 2020-11, with the labels that each got.

#14 10 fazer documento de arquitetura
  docs/images/architecture.png
  docs/projeto/doc_arquitetura.md
Labels: documentation, hacktoberfest-accepted

#15 #11 fazer documento visao
  docs/produto/doc_visao.md
Labels: documentation

#19 #17 adicionar git_pages
  docs/README.md
  docs/_sidebar.md
  docs/index.html
Labels: enhancement

#21 #20 adicionar tap
  README.md
  docs/README.md
  docs/_sidebar.md
  docs/images/milestone_chart.png
  docs/produto/visao.md
  docs/projeto/arquitetura.md
  docs/projeto/planejamento/cronograma_milestone.md
  docs/projeto/planejamento/planejamento.md
  docs/projeto/planejamento/tap.md
Labels: documentation, enhancement

#25 #24 Adiciona roadmap de papeis
  docs/_sidebar.md
  docs/projeto/planejamento/roadmap.md
  docs/projeto/planejamento/roadmapPapeis.md
Labels: documentation

#27 #26 adicionar plano de risco
  docs/_sidebar.md
  docs/projeto/planejamento/risco.md
Labels: documentation

#35 #34 correcao de doc
  docs/projeto/planejamento/planejamento.md
  docs/projeto/sprint/03/planejamento.md
  docs/projeto/sprint/03/resultado.md
  docs/projeto/sprint/04/planejamento.md
  docs/projeto/sprint/04/resultado.md
  docs/projeto/sprint/05/planejamento.md
Labels: bug, documentation

#33 #8 criar labels
  api/app/controllers/label.controller.js
  api/app/models/index.js
  api/app/models/label.models.js
  api/app/routes/tutorial.routes.js
Labels: enhancement
